# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/A37/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),A37)

include $(CLEAR_VARS)
LOCAL_MODULE := dolby_ds
LOCAL_MODULE_OWNER := lenovo
LOCAL_SRC_FILES := proprietary/system/framework/dolby_ds.jar
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Ds
LOCAL_MODULE_OWNER := lenovo
LOCAL_SRC_FILES := proprietary/system/priv-app/Ds/Ds.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := DsUI
LOCAL_MODULE_OWNER := lenovo
LOCAL_SRC_FILES := proprietary/system/priv-app/DsUI/DsUI.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

endif
